# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlockerExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BlockerExtension

end

target 'HelloGoodbyeiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloGoodbyeiOS

end
